name: 02-workflow-events

on:
  # - push
  - workflow_dispatch

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Name of the event is ${{github.event_name}}"
