name: 05- Using Functions
on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        default: 'RUN'

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: I will execute
        if: ${{!cancelled()}}
        run: |
          echo 'I will always print except when its cancelled'
          echo ${{inputs.title}}
      - name: Run this if title equals RUN
        if: contains('RUN', inputs.title)
        run: echo "Title value is RUN and hence running this step"
