name: 08- Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        description: 'Status of the build job'
        type: choice
        options:
          - success
          - failure
          - skipped
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outputs.build_status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "GITHUB_OUTPUT path is $GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "Build job status: ${{ github.event.inputs.build-status }}"
          echo "build_status=${{ github.event.inputs.build-status }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build_status == 'success' }}
    steps:
      - name: Deploy
        run: 'echo "Deploying the application with build status: ${{ needs.build.outputs.build_status }}"'
